name: Unzip, run and cleanup

on:
  workflow_dispatch:

jobs:
  run-python-zip:
    runs-on: ubuntu-latest
    env:
      ZIP_PASS: ${{ secrets.ZIP_PASS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files before unzip
        run: ls -la

      - name: Unzip protected zip
        run: unzip -P "$ZIP_PASS" file.zip

      - name: List files after unzip
        run: ls -la

      - name: Run Python script
        run: python file.py

      - name: Cleanup - remove script
        run: rm -f file.py
